baseURL = "https://co-mission.co/"
languageCode = "en-us"
title = "Co-Mission.co"
theme = "LoveIt"
enableRobotsTXT = true

[pagination]
  pagerSize = 10

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  defaultTheme = "light"
  disableThemeToggle = true
  description = "Co-Mission: True Missions Happen in Connection"

  [params.header]
    [params.header.title]
      name = "Co-Mission"

[params.page]
  [params.page.library]
    [params.page.library.css]
      custom = "css/custom.css"
    [params.page.library.js]
      slogan = "js/slogan.js"

[[menu.main]]
  name = "Home"
  url = "#top"
  weight = 10

[[menu.main]]
  name = "Our Story"
  url = "#our-story"
  weight = 20

[[menu.main]]
  name = "How We Co-Mission"
  url = "#how-we-co-mission"
  weight = 30

[[menu.main]]
  name = "Our Co-Missions"
  url = "#our-co-missions"
  weight = 40

[[menu.main]]
  name = "Contact"
  url = "#connect"
  weight = 50
